import '../models/product_model.dart';
import '../models/order_model.dart';
import '../models/user_model.dart';

class MockDataService {
  static final UserModel defaultArtisanUser = UserModel(
    id: 1,
    name: 'Asha Devi',
    email: 'asha.devi@kalasetu.in',
    phone: '+91 98765 43210',
    role: UserRoleType.artisan,
    artisanProfile: ArtisanProfileModel(
      fullName: 'Asha Devi',
      bio: 'Master terracotta artisan preserving 4 generations of Blue Pottery & Glazed Clay heritage in Sanganer.',
      craftType: 'Pottery',
      experienceYears: 18,
      state: 'Rajasthan',
      district: 'Jaipur',
      village: 'Sanganer',
      profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&q=80',
    ),
  );

  static final UserModel defaultCustomerUser = UserModel(
    id: 2,
    name: 'Meera Shah',
    email: 'meera.shah@gmail.com',
    phone: '+91 98765 43210',
    role: UserRoleType.customer,
  );

  static List<ProductModel> getInitialProducts() {
    return [
      ProductModel(
        id: 101,
        name: 'Indigo Glaze Serving Bowl',
        description: 'Wheel-thrown by hand and finished with a deep indigo glaze. Every piece carries gentle variations that make it truly one of a kind. Crafted with organic clay sourced from local riverbeds and fired in a wood-burning kiln.',
        price: 1499.0,
        category: 'Pottery',
        stock: 14,
        state: 'Rajasthan',
        sellerId: 1,
        sellerName: 'Asha Devi',
        sellerTitle: 'Master Potter',
        sellerLocation: 'Jaipur, Rajasthan',
        imageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&q=80',
        tags: ['#pottery', '#handmade', '#indigo'],
        material: 'Terracotta',
        madeIn: 'Jaipur, Rajasthan',
        rating: 4.9,
        reviewCount: 32,
      ),
      ProductModel(
        id: 102,
        name: 'Moonj Storage Basket',
        description: 'Handcrafted using wild Moonj and Kaasa grass collected sustainably from the riverbanks. Woven intricately with ancient coiling techniques, perfect for modern bohemian home storage.',
        price: 1290.0,
        category: 'Baskets',
        stock: 8,
        state: 'Uttar Pradesh',
        sellerId: 2,
        sellerName: 'Savitri Devi',
        sellerTitle: 'Grass Weaving Artisan',
        sellerLocation: 'Prayagraj, UP',
        imageUrl: 'https://images.unsplash.com/photo-1584589167171-541ce45f1eea?w=800&q=80',
        tags: ['#baskets', '#ecofriendly', '#naturalgrass'],
        material: 'Moonj Grass',
        madeIn: 'Prayagraj, Uttar Pradesh',
        rating: 4.8,
        reviewCount: 19,
      ),
      ProductModel(
        id: 103,
        name: 'Blue Glaze Kulhad (Set of 2)',
        description: 'Traditional Indian tea cups elevated with handcrafted indigo mineral slip. Enhances the earthy aroma of masala chai with its breathable natural terracotta base.',
        price: 849.0,
        category: 'Pottery',
        stock: 25,
        state: 'Rajasthan',
        sellerId: 1,
        sellerName: 'Asha Devi',
        sellerTitle: 'Master Potter',
        sellerLocation: 'Jaipur, Rajasthan',
        imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80',
        tags: ['#pottery', '#chai', '#kulhad'],
        material: 'Clay & Indigo Slip',
        madeIn: 'Jaipur, Rajasthan',
        rating: 5.0,
        reviewCount: 47,
      ),
      ProductModel(
        id: 104,
        name: 'Terracotta Planter',
        description: 'Porous terracotta planter with hand-carved floral lattice motifs. Promotes healthy root aeration and moisture regulation for indoor and balcony plants.',
        price: 899.0,
        category: 'Pottery',
        stock: 12,
        state: 'Rajasthan',
        sellerId: 1,
        sellerName: 'Asha Devi',
        sellerTitle: 'Master Potter',
        sellerLocation: 'Jaipur, Rajasthan',
        imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80',
        tags: ['#pottery', '#planter', '#gardening'],
        material: 'Terracotta',
        madeIn: 'Jaipur, Rajasthan',
        rating: 4.7,
        reviewCount: 15,
      ),
      ProductModel(
        id: 105,
        name: 'Ajrakh Handblock Dupatta',
        description: 'Handblock printed pure modal silk dupatta using 16-step natural mud resist dyeing techniques with pomegranate and wild indigo extracts.',
        price: 2450.0,
        category: 'Textiles',
        stock: 6,
        state: 'Gujarat',
        sellerId: 3,
        sellerName: 'Ismail Khatri',
        sellerTitle: 'Ajrakh Master',
        sellerLocation: 'Kutch, Gujarat',
        imageUrl: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&q=80',
        tags: ['#textiles', '#ajrakh', '#naturaldye'],
        material: 'Modal Silk',
        madeIn: 'Kutch, Gujarat',
        rating: 4.9,
        reviewCount: 22,
      ),
      ProductModel(
        id: 106,
        name: 'Dhokra Brass Tribal Bell',
        description: 'Lost-wax cast bronze bell fashioned by Bastar tribal artisans. Features resonant chime and symbolic folk motifs honoring sacred forest spirits.',
        price: 1850.0,
        category: 'Jewellery',
        stock: 5,
        state: 'Chhattisgarh',
        sellerId: 4,
        sellerName: 'Mangal Ram',
        sellerTitle: 'Dhokra Artisan',
        sellerLocation: 'Bastar, Chhattisgarh',
        imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80',
        tags: ['#jewellery', '#dhokra', '#brass'],
        material: 'Bell Metal / Brass',
        madeIn: 'Bastar, Chhattisgarh',
        rating: 4.8,
        reviewCount: 11,
      ),
    ];
  }

  static List<OrderModel> getInitialOrders() {
    return [
      OrderModel(
        id: 1,
        orderCode: '#AX1048',
        userId: 2,
        productId: 101,
        productName: 'Indigo Serving Bowl',
        artisanName: 'Asha Devi',
        quantity: 1,
        totalPrice: 1499.0,
        status: OrderStatus.readyToShip,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      OrderModel(
        id: 2,
        orderCode: '#AX1043',
        userId: 3,
        productId: 103,
        productName: 'Set of 2 Kulhads',
        artisanName: 'Asha Devi',
        quantity: 1,
        totalPrice: 1198.0,
        status: OrderStatus.processing,
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      OrderModel(
        id: 3,
        orderCode: '#AX1039',
        userId: 4,
        productId: 104,
        productName: 'Terracotta Planter',
        artisanName: 'Asha Devi',
        quantity: 1,
        totalPrice: 899.0,
        status: OrderStatus.delivered,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
    ];
  }
}
